#!/bin/bash
# Vercel Build Script
# Runs during `vercel build` — generates env.js with runtime config
# Set these in Vercel Dashboard → Project → Settings → Environment Variables:
#   MAPQUEST_KEY   → your MapQuest API key
#   BACKEND_URL    → https://your-app.onrender.com  (NO trailing slash)

set -e

echo "Generating env.js from environment variables..."

cat > env.js << EOF
// Auto-generated by build.sh — do not edit manually
window.ENV = {
  MAPQUEST_KEY: "${MAPQUEST_KEY}",
  BACKEND_URL:  "${BACKEND_URL}"
};
EOF

echo "env.js generated:"
cat env.js
echo ""
echo "Build complete."