services:
  - type: web
    name: physician-locator-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --worker-class gthread --timeout 120 --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: MAPQUEST_API_KEY
        sync: false
      - key: GEOAPIFY_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SF_OID
        value: "00DHs00000P5yok"
      - key: SF_RET_URL
        value: "https://physicians-locator-tigulladeepika12-9621s-projects.vercel.app"
      - key: SF_DEBUG_EMAIL
        value: "deepika.tigulla@aquarient.com"